### ISSUE TITLE
Social feed, Tip Section TORI price under the USD price.

### ISSUE THREAD

**Issue by omniwired** [TERITORI/teritori-dapp#555]
Please add TORI price under the USD price.

![image](https://user-images.githubusercontent.com/322761/232009656-2819d9c9-b64e-4f3b-ac45-5d553239aca0.png)

**Comment by an78mK89fy** [comment]
As the price of teri drops, more and more teri tokens are likely to be paid, but the value of the dollar does not change or even goes down, causing confusion for those who pay
Maybe you should also add the teri price chart, and the percentage rise and fall
Or change the primary display to teri, dollar value as a secondary display, so that more currency value conversion can be added in the future

**Comment by n0izn0iz** [comment]
won't do

**Comment by n0izn0iz** [comment]
maybe will do but very low prio
