### ISSUE TITLE
Launchpad: Fix mints sort by smartcontract deployment date

### ISSUE THREAD

**Issue by FerrymanGMI** [TERITORI/teritori-dapp#569]
Sort the collection cards by date of contract deployment, the latest deployment should be the first card and the first deployment should be at the bottom of the grid.
![image](https://user-images.githubusercontent.com/76942962/232736618-805ee396-8f35-41f9-8cc7-b2b7d397c0d3.png)

**Comment by omniwired** [comment]
currently is using this line
https://github.com/TERITORI/teritori-dapp/blob/f671862119ae90d225fd55d7aa4b39f800079a86/go/pkg/marketplace/marketplace_service.go#L147

This means that if the problem is on the function
https://github.com/TERITORI/teritori-dapp/blob/2027e5c1c520aa8222592ada998d522ee71c830d/go/internal/indexerhandler/utils.go#L143

**Comment by omniwired** [comment]
I found an exact block where this problem happens:

Please have a look @n0izn0iz @hthieu1110 

![image](https://user-images.githubusercontent.com/322761/232979866-c17426c6-7a3c-4184-ad55-406bba9302b9.png)

The problem seem to be happening on the cache path.
You can check block height: 1729748 in testnet

**Comment by n0izn0iz** [comment]
what is the problem with blockTime ?
activities use it and are properly sorted

**Comment by omniwired** [comment]
@n0izn0iz I don't see how to do it via contract deployment date.
I was relying on the indexer and the `collection` table and the time field.

**Comment by omniwired** [comment]
> what is the problem with blockTime ? activities use it and are properly sorted

yes, it seems related but it wasn't only TNS have time 0000

**Comment by n0izn0iz** [comment]
oh ok, yeah it's not set in tns handler code
